### ISSUE TITLE
unable to generate a new gwas catalog

### ISSUE THREAD

**Issue by mabelwang21** [welchr/swiss#11]
#### Command-line used to cause the issue

```
/usr/local/python-2.7/bin/swiss-create-data --gwas-cat --genome-build GRCh37p13 --dbsnp-build b147

```

#### Problem description
I am not able to create a new gwas catalog using swiss-create-data command. It may be relate to the 'NCBI_VCF_TEMPLATE_URL' in create_data.py. When I try to find the VCF file myself, the URL (ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/00-All.vcf.gz) does not include genome build and dbSNP build.

#### Program output

Genome build: GRCh37p13
dbSNP build: b147
Downloading rsID merge history...
RsMergeArch.bcp.gz: 0.00B [00:00, ?B/s]
Traceback (most recent call last):
  File "/usr/local/python-2.7/bin/swiss-create-data", line 22, in <module>
    main()
  File "/usr/local/python-2.7/lib/python2.7/site-packages/swiss/create_data.py", line 593, in main
    rsmerge_path = download_merge_arch()
  File "/usr/local/python-2.7/lib/python2.7/site-packages/swiss/create_data.py", line 85, in download_merge_arch
    urlretrieve(url,filename=outpath,reporthook=tqdm_hook(t),data=None)
  File "/usr/local/python-2.7/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/local/python-2.7/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/local/python-2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/local/python-2.7/lib/python2.7/urllib.py", line 550, in open_ftp
    ftpwrapper(user, passwd, host, port, dirs)
  File "/usr/local/python-2.7/lib/python2.7/urllib.py", line 877, in __init__
    self.init()
  File "/usr/local/python-2.7/lib/python2.7/urllib.py", line 889, in init
    self.ftp.cwd(_target)
  File "/usr/local/python-2.7/lib/python2.7/ftplib.py", line 574, in cwd
    return self.voidcmd(cmd)
  File "/usr/local/python-2.7/lib/python2.7/ftplib.py", line 256, in voidcmd
    return self.voidresp()
  File "/usr/local/python-2.7/lib/python2.7/ftplib.py", line 231, in voidresp
    resp = self.getresp()
  File "/usr/local/python-2.7/lib/python2.7/ftplib.py", line 226, in getresp
    raise error_perm, resp
IOError: [Errno ftp error] 550 snp/database/organism_data/human_9606: No such file or directory

#### Swiss version
1.0b4

**Comment by welchr** [comment]
Looks like they deleted b147: ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/

If you try `--dbsnp-build b150` does it work then?

**Comment by mabelwang21** [comment]
No, it doesn't work. The error message is the same as using b147. Please see below:

Genome build: GRCh37p13
dbSNP build: b150
Downloading rsID merge history...
RsMergeArch.bcp.gz: 0.00B [00:00, ?B/s]
Traceback (most recent call last):
  File "/usr/local/python-2.7/bin/swiss-create-data", line 22, in <module>
    main()
  File "/usr/local/python-2.7/lib/python2.7/site-packages/swiss/create_data.py", line 593, in main
    rsmerge_path = download_merge_arch()
  File "/usr/local/python-2.7/lib/python2.7/site-packages/swiss/create_data.py", line 85, in download_merge_arch
    urlretrieve(url,filename=outpath,reporthook=tqdm_hook(t),data=None)
  File "/usr/local/python-2.7/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/local/python-2.7/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/local/python-2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/local/python-2.7/lib/python2.7/urllib.py", line 550, in open_ftp
    ftpwrapper(user, passwd, host, port, dirs)
  File "/usr/local/python-2.7/lib/python2.7/urllib.py", line 877, in __init__
    self.init()
  File "/usr/local/python-2.7/lib/python2.7/urllib.py", line 889, in init
    self.ftp.cwd(_target)
  File "/usr/local/python-2.7/lib/python2.7/ftplib.py", line 574, in cwd
    return self.voidcmd(cmd)
  File "/usr/local/python-2.7/lib/python2.7/ftplib.py", line 256, in voidcmd
    return self.voidresp()
  File "/usr/local/python-2.7/lib/python2.7/ftplib.py", line 231, in voidresp
    resp = self.getresp()
  File "/usr/local/python-2.7/lib/python2.7/ftplib.py", line 226, in getresp
    raise error_perm, resp
IOError: [Errno ftp error] 550 snp/database/organism_data/human_9606: No such file or directory

------------------------------------------------------------------------------------------------------
In create_data.py:
line 37: NCBI_VCF_TEMPLATE_URL = "ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_{0}_{1}/VCF/00-All.vcf.gz"
line 119: url = NCBI_VCF_TEMPLATE_URL.format(dbsnp_build,genome_build)

But the actual URL of the vcf file (ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/00-All.vcf.gz) does not include genome build and dbSNP build?

**Comment by welchr** [comment]
Actually, in your case I think it might be the old swiss version (1.0b4 vs 1.0). The error above is happening when it tries to download RsMergeArch.bcp.gz, and we had to change the URL for that back in f7a1c6b4918127beaaf013c7943e26a03c35f2e5. 

If you upgrade to the latest swiss and still have an issue, please let me know.

**Comment by mabelwang21** [comment]
Thank you for the suggestion!

I have upgraded to the latest swiss (v1.1.0) and able to download the files. Unfortunately, there is an error when parsing/reformatting GWAS catalog. Please let me know if you have any suggestions. Thank you again! 

-------------------------------------------------------------------------------------------------------------
$ swiss-create-data --gwas-cat --genome-build GRCh37p13 --dbsnp-build b150
Genome build: GRCh37p13
dbSNP build: b150
Downloading rsID merge history...
RsMergeArch.bcp.gz: 153MB [00:13, 11.5MB/s]                                                                                                                                                                        
Downloading rsID deletion history...
SNPHistory.bcp.gz: 106MB [00:09, 10.9MB/s]                                                                                                                                                                         
Downloading NCBI dbSNP VCF for b150 / GRCh37p13 @ ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b150_GRCh37p13/VCF/00-All.vcf.gz
00-All.vcf.gz:                                                                                                                                                                            
Parsing histories...
Creating database...
Parsing VCF: human_9606_b150_GRCh37p13_All.vcf.gz
Creating indexes...
CREATE INDEX idx_snp ON dbsnp (rsid)
CREATE INDEX idx_chrpos ON dbsnp (chrpos)
CREATE INDEX idx_chrom_and_pos ON dbsnp (chrom,pos)
CREATE INDEX idx_epacts ON dbsnp (epacts)
Creating SNP translation table..
Creating indexes...
CREATE INDEX idx_rs_orig ON trans (rs_orig)
CREATE INDEX idx_rs_current ON trans (rs_current)

Database successfully created: GRCh37p13_b150.sqlite
Downloading GWAS catalog..
full: 88.7MB [00:12, 7.26MB/s]

Parsing/reformatting GWAS catalog..
147331line [29:26, 83.40line/s]Traceback (most recent call last):
  File "/projects/lindstroem/programs/swiss/bin/swiss-create-data", line 22, in <module>
    main()
  File "/projects/lindstroem/programs/swiss/lib/python2.7/site-packages/swiss/create_data.py", line 692, in main
    parse_gwas_catalog(tmp_gwascat,db_name,final_gwas_cat)
  File "/projects/lindstroem/programs/swiss/lib/python2.7/site-packages/swiss/create_data.py", line 363, in parse_gwas_catalog
    vrecord = swiss_db.rsid_to_variant(rsid)
  File "/projects/lindstroem/programs/swiss/lib/python2.7/site-packages/swiss/create_data.py", line 224, in rsid_to_variant
    cur1 = self.db.execute("SELECT * FROM trans_view WHERE rsid='{}'".format(variant))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2020' in position 9: ordinal not in range(128)

**Comment by welchr** [comment]
Hmm, now it looks like a unicode problem. Strange that the variant itself would have that issue, usually it's the author names that need special care. I'll take a look.

**Comment by welchr** [comment]
@mabelwang21 Hopefully this does the trick. Try updating to version 1.1.1. Please let me know if you run into any other issues.

**Comment by mabelwang21** [comment]
Thank you, it works now!
