### ISSUE TITLE
UCS2 vs UCS4

### ISSUE THREAD

**Issue by ariza-droid** [welchr/swiss#13]
#### Problem description
Compiler problem. UCS2 vs UCS4

#### Program output
> swiss --version
Traceback (most recent call last):
  File "~/.local/bin/swiss", line 18, in <module>
    from swiss.main import main
  File "~/.local/lib/python2.7/site-packages/swiss/main.py", line 40, in <module>
    from LDClumper import *
  File "~/.local/lib/python2.7/site-packages/swiss/LDClumper.py", line 20, in <module>
    from AssocResults import *
  File "~/.local/lib/python2.7/site-packages/swiss/AssocResults.py", line 23, in <module>
    from bx.intervals.intersection import *
  File "~/.local/lib/python2.7/site-packages/bx/intervals/__init__.py", line 7, in <module>
    from bx.intervals.intersection import *  # noqa: F40
ImportError: ~/.local/lib/python2.7/site-packages/bx/intervals/intersection.so: undefined symbol: PyUnicodeUCS2_FromStringAndSize

>python
Python 2.7.18rc1 (default, Apr  7 2020, 12:05:55)
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.maxunicode
1114111
>>> quit()
Which shows I am using UCS4

Would you kindly be able to suggest approaches to sort this out, please?

**Comment by welchr** [comment]
Seems similar to this: https://stackoverflow.com/questions/11878666/python-undefined-symbol-pyunicodeucs2-decodeutf8

Are you running multiple installations of python on the same system? Try `which -a python` and `which -a python2` to see how many python interpreters are on your PATH. 

You'll want to ensure you are installing/compiling the package and running it with the exact same python.

**Comment by ariza-droid** [comment]
May have rushed to conclusions. At the time, indeed, the system I was
trying swiss on had both python3 (since it comes with Ubuntu 20) and
python2 installed, with alternatives set and priority set to python2.

Regardless, I tried a fresh start on a new virtual machine (for sudo
privileges), used snapshots to change several times the order in which I
installed/compiled several of the software/dependencies/compilers, gcc etc.
All of this to say it worked and I have no idea what was significantly
different this time. I will not dwell any more on this, but get on to
making the machine work for me, rather than the reverse. All not before
thanking you for your prompt response and help with troubleshooting. Last
but not least, thank you and your team for developing these tools, as well
as making them available!

Best wishes,
Anca Riza
