### ISSUE TITLE
KeyError problem on PVALUE

### ISSUE THREAD

**Issue by oyhel** [welchr/swiss#2]
#### Command-line used to cause the issue
swiss --assoc ../analyses/results.swissformat --build hg19 --ld-clump-source 1000G_2012-03_EUR --ld-gwas-source 1000G_2012-03_EUR --gwas-cat ebi --clump-p 5e-6 --out test1

#### Path to your data (if publicly available)
Not available but dummy format as such:
CHR     POS     REF     ALT     MARKER_ID       PVALUE
1       762409  G       C       1:762409_G/C    0.106546
1       763394  G       A       1:763394_G/A    0.411471
1       766007  A       C       1:766007_A/C    0.829445
1       768253  A       C       1:768253_A/C    0.978769
1       768448  G       A       1:768448_G/A    0.671478
1       768819  C       T       1:768819_C/T    0.498841
1       769223  C       G       1:769223_C/G    0.389215
1       769479  G       C       1:769479_G/C    0.881084
1       769885  G       A       1:769885_G/A    0.982786

#### Problem description
When testing the swiss tool I run into a keyerror problem in pandas on key "PVALUE". Not sure what exactly the problem is. I've added the stack trace.

###Stack trace:
Loading results file: ../analyses/results.swissformat
Traceback (most recent call last):
  File "/media/local-disk2/hg/swiss-test/swiss/bin/swiss", line 20, in <module>
    main()
  File "/media/local-disk2/hg/swiss-test/swiss/local/lib/python2.7/site-packages/swiss/main.py", line 1022, in main
    run_process(opts.assoc,opts.trait,opts.out,opts)
  File "/media/local-disk2/hg/swiss-test/swiss/local/lib/python2.7/site-packages/swiss/main.py", line 765, in run_process
    results.load(sep=opts.delim)
  File "/media/local-disk2/hg/swiss-test/swiss/local/lib/python2.7/site-packages/swiss/AssocResults.py", line 136, in load
    chunk = chunk[chunk[self.pval_col] < self.pval_thresh]
  File "/media/local-disk2/hg/swiss-test/swiss/local/lib/python2.7/site-packages/pandas/core/frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "/media/local-disk2/hg/swiss-test/swiss/local/lib/python2.7/site-packages/pandas/core/frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "/media/local-disk2/hg/swiss-test/swiss/local/lib/python2.7/site-packages/pandas/core/generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "/media/local-disk2/hg/swiss-test/swiss/local/lib/python2.7/site-packages/pandas/core/internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "/media/local-disk2/hg/swiss-test/swiss/local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5280)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20523)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20477)
KeyError: 'PVALUE'

#### Swiss version
 1.0b4

**Comment by welchr** [comment]
Might be just a file delimiter issue. Are your results space delimited instead of tab delimited? Try using the `--delim` option, possible values are `tab`, `space`, `whitespace`, or a regular expression.

**Comment by oyhel** [comment]
Thank you! This turned out to be a delimiter issue. I have one other problem but for tidyness I'll open another issue.
