### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by gpcr** [welchr/swiss#9]
#### Command-line used to cause the issue
swiss --assoc test_hg19.gz --ld-clump --clump-p 5e-06 --out my_results

```
swiss --assoc file.txt ...
```

#### Path to your data (if publicly available)

http://path/to/your/data/

#### Problem description

Please describe the issue: 

aborted with below error message

* What is the problem? 
* Is it reproducible? 
* What was the expected output? 

#### Program output

* What did the program output? Was there an error message?

Traceback (most recent call last):
  File "/usr/local/bin/swiss", line 20, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/swiss/main.py", line 962, in main
    (opts,args) = get_settings(arg_string)
  File "/usr/local/lib/python2.7/dist-packages/swiss/main.py", line 544, in get_settings
    check_plink_version(opts.plink_path)
  File "/usr/local/lib/python2.7/dist-packages/swiss/main.py", line 286, in check_plink_version
    x, y, beta, z = re.search("v(\d+)\.(\d+)b?(\d+)?\.(\w+)",version_string).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

#### Swiss version
1.0b4
plink --version
PLINK v1.90b5 64-bit (14 Nov 2017)

If you don't know your swiss version, please do: 

```bash
swiss --version
```

**Comment by welchr** [comment]
Looks like a bug that was fixed earlier this year (#7). Try updating to the [latest version](https://github.com/statgen/swiss/releases) and see if you still see the same error.

**Comment by gpcr** [comment]
Now I get this error
$ swiss --assoc test_hg19.gz --ld-clump --clump-p 5e-06 --out my_results
+-----------------------------------+
|           Swiss - 1.0.0           |
+-----------------------------------+
|   Ryan Welch (welchr@umich.edu)   |
+-----------------------------------+
|  https://github.com/welchr/Swiss  |
+-----------------------------------+

Loading results file: test_hg19.gz
Traceback (most recent call last):
  File "/usr/local/bin/swiss", line 20, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/swiss/main.py", line 1064, in main
    run_process(opts.assoc,opts.trait,opts.out,opts)
  File "/usr/local/lib/python2.7/dist-packages/swiss/main.py", line 791, in run_process
    results.load(sep=opts.delim)
  File "/usr/local/lib/python2.7/dist-packages/swiss/AssocResults.py", line 157, in load
    chunk = chunk[chunk[self.pval_col] < self.pval_thresh]
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 3843, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/indexes/base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'PVALUE'

**Comment by welchr** [comment]
If that's the same `test_hg19.gz` from the test directory, you can look at the tests to see the various command lines used: 

https://github.com/statgen/swiss/blob/9ae335a3326e2b7ecb923c3c4427117f843eb326/test/test_cases.py#L39-L43

That particular file is in "multi-assoc" format, where there are multiple p-value and effect size columns, one set per trait tested.

**Comment by gpcr** [comment]
yes, same file from the test folder
Thanks!!!! 

Working fine with below command

`swiss --assoc test_hg19.gz --multi-assoc --build hg19 --ld-clump-source 1000G_2014-11_ALL --ld-gwas-source 1000G_2014-11_ALL --gwas-cat gwascat_ebi_GRCh37p13.tab --ld-clump --clump-p 5e-06 --out my_results
`
